name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.4.7', '2.5.6', '2.6.5', '2.7.0', 'truffleruby' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: eregon/use-ruby-action@master
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install
    - run: bundle exec rspec
